name: npm package access

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  make-public:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
          scope: '@attomus'

      - name: Mark package public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm access public @attomus/semafore-crypto
